library(xpectr)
context("create_expectations")

test_that("expectation are created properly with create_expectations_data_frame()", {
  df1 <- tibble::tibble("a" = c(1, 2, 3, 4), "b" = c("a", "f", "g", "s"))
  df1$c <- list(list(1, 2, 3), list(2, 3, 4, 5), list(2, 3, 7, 21, 2), list(2))
  df1[["d"]] <- list(a = list(2, 4), b = list(3), c = list(1), d = list(2, 3))
  # Add factor
  df1$f <- factor(df1$a)

  # We're not getting it from parent environment
  # so we supply current environment
  current_envir <- sys.frame(which = sys.nframe())

  expect_warning(expts <- create_expectations_data_frame(df1),
    "Skipped columns c, d.",
    fixed = TRUE
  )
  expts_expected <- list(
    "## Testing 'df1'                                                            ####\n## Initially generated by xpectr",
    "# Testing class",
    "expect_equal(\n  class(df1),\n  c(\"tbl_df\", \"tbl\", \"data.frame\"),\n  fixed = TRUE)",
    "# Testing column values",
    "expect_equal(\n  df1[[\"a\"]],\n  c(1, 2, 3, 4),\n  tolerance = 1e-4)",
    "expect_equal(\n  df1[[\"b\"]],\n  c(\"a\", \"f\", \"g\", \"s\"),\n  fixed = TRUE)",
    "expect_equal(\n  df1[[\"f\"]],\n  structure(1:4, .Label = c(\"1\", \"2\", \"3\", \"4\"), class = \"factor\"))",
    "# Testing column names",
    "expect_equal(\n  names(df1),\n  c(\"a\", \"b\", \"c\", \"d\", \"f\"),\n  fixed = TRUE)",
    "# Testing column classes",
    "expect_equal(\n  unlist(lapply(df1, class), use.names = FALSE),\n  c(\"numeric\", \"character\", \"list\", \"list\", \"factor\"),\n  fixed = TRUE)",
    "# Testing column types",
    "expect_equal(\n  unlist(lapply(df1, typeof), use.names = FALSE),\n  c(\"double\", \"character\", \"list\", \"list\", \"integer\"),\n  fixed = TRUE)",
    "# Testing dimensions",
    "expect_equal(\n  dim(df1),\n  4:5)",
    "# Testing group keys",
    "expect_equal(\n  colnames(dplyr::group_keys(df1)),\n  character(0),\n  fixed = TRUE)",
    "## Finished testing 'df1'                                                   ####"
  )

  expect_equal(
    expts,
    expts_expected
  )
  eval_expectations(expts_expected, envir = current_envir)
})

test_that("expectation are created properly with create_expectations_vector()", {
  vec_1 <- c(1, 2, 3, 4)
  vec_2 <- c("a" = 10, "b" = 20, "c" = 30)
  vec_3 <- c("a" = c(10, 2, 4), "b" = c(20, 1, 3), "c" = c(2, 3, 30))
  vec_4 <- c("a" = list(10, 2, 4), "b" = list(20, 1, 3), "c" = list(2, 3, 30))
  vec_5 <- list("a" = list(10, 2, 4), "b" = list(20, 1, 3), "c" = list(2, 3, 30))
  vec_6 <- list("a" = list(10, 2, 4), "b" = list(20, 1, 3), list(2, 3, 30))
  vec_7 <- list(5, 6, 7, 8)

  # We're not getting it from parent environment
  # so we supply current environment
  current_envir <- sys.frame(which = sys.nframe())

  # Vec 1

  exp_vec_1 <- list(
    "## Testing 'vec_1'                                                          ####\n## Initially generated by xpectr",
    "# Testing class",
    "expect_equal(\n  class(vec_1),\n  \"numeric\",\n  fixed = TRUE)",
    "# Testing type",
    "expect_type(\n  vec_1,\n  type = \"double\")",
    "# Testing values",
    "expect_equal(\n  vec_1,\n  c(1, 2, 3, 4),\n  tolerance = 1e-4)",
    "# Testing names",
    "expect_equal(\n  names(vec_1),\n  NULL,\n  fixed = TRUE)",
    "# Testing length",
    "expect_equal(\n  length(vec_1),\n  4L)",
    "# Testing sum of element lengths",
    "expect_equal(\n  sum(unlist(lapply(vec_1, length))),\n  4L)",
    "## Finished testing 'vec_1'                                                 ####"
  )

  expect_equal(
    create_expectations_vector(vec_1),
    exp_vec_1)

  eval_expectations(exp_vec_1, current_envir)


  # Vec 2

  exp_vec_2 <- list(
    "## Testing 'vec_2'                                                          ####\n## Initially generated by xpectr",
    "# Testing class",
    "expect_equal(\n  class(vec_2),\n  \"numeric\",\n  fixed = TRUE)",
    "# Testing type",
    "expect_type(\n  vec_2,\n  type = \"double\")",
    "# Testing values",
    "expect_equal(\n  vec_2,\n  c(a = 10, b = 20, c = 30),\n  tolerance = 1e-4)",
    "# Testing names",
    "expect_equal(\n  names(vec_2),\n  c(\"a\", \"b\", \"c\"),\n  fixed = TRUE)",
    "# Testing length",
    "expect_equal(\n  length(vec_2),\n  3L)",
    "# Testing sum of element lengths",
    "expect_equal(\n  sum(unlist(lapply(vec_2, length))),\n  3L)",
    "## Finished testing 'vec_2'                                                 ####"
  )

  expect_equal(
    create_expectations_vector(vec_2),
    exp_vec_2
  )
  eval_expectations(exp_vec_2, current_envir)


  # Vec 3

  exp_vec_3 <- list(
    "## Testing 'vec_3'                                                          ####\n## Initially generated by xpectr",
    "# Testing class",
    "expect_equal(\n  class(vec_3),\n  \"numeric\",\n  fixed = TRUE)",
    "# Testing type",
    "expect_type(\n  vec_3,\n  type = \"double\")",
    "# Testing values",
    "expect_equal(\n  vec_3,\n  c(a1 = 10, a2 = 2, a3 = 4, b1 = 20, b2 = 1, b3 = 3, c1 = 2, c2 = 3, c3 = 30),\n  tolerance = 1e-4)",
    "# Testing names",
    "expect_equal(\n  names(vec_3),\n  c(\"a1\", \"a2\", \"a3\", \"b1\", \"b2\", \"b3\", \"c1\", \"c2\", \"c3\"),\n  fixed = TRUE)",
    "# Testing length",
    "expect_equal(\n  length(vec_3),\n  9L)",
    "# Testing sum of element lengths",
    "expect_equal(\n  sum(unlist(lapply(vec_3, length))),\n  9L)",
    "## Finished testing 'vec_3'                                                 ####"
  )

  expect_equal(
    create_expectations_vector(vec_3),
    exp_vec_3
  )
  eval_expectations(exp_vec_3, current_envir)


  # Vec 4
  exp_vec_4 <- list(
    "## Testing 'vec_4'                                                          ####\n## Initially generated by xpectr",
    "# Testing class",
    "expect_equal(\n  class(vec_4),\n  \"list\",\n  fixed = TRUE)",
    "# Testing type",
    "expect_type(\n  vec_4,\n  type = \"list\")",
    "# Testing values",
    "expect_equal(\n  vec_4,\n  list(a1 = 10, a2 = 2, a3 = 4, b1 = 20, b2 = 1, b3 = 3, c1 = 2,     c2 = 3, c3 = 30))",
    "# Testing names",
    "expect_equal(\n  names(vec_4),\n  c(\"a1\", \"a2\", \"a3\", \"b1\", \"b2\", \"b3\", \"c1\", \"c2\", \"c3\"),\n  fixed = TRUE)",
    "# Testing length",
    "expect_equal(\n  length(vec_4),\n  9L)",
    "# Testing sum of element lengths",
    "expect_equal(\n  sum(unlist(lapply(vec_4, length))),\n  9L)",
    "## Finished testing 'vec_4'                                                 ####"
  )

  expect_equal(
    create_expectations_vector(vec_4, tolerance = "1e-5"),
    exp_vec_4
  )
  eval_expectations(exp_vec_4, current_envir)

  # vec_5
  exp_vec_5 <- list(
    "## Testing 'vec_5'                                                          ####\n## Initially generated by xpectr",
    "# Testing class",
    "expect_equal(\n  class(vec_5),\n  \"list\",\n  fixed = TRUE)",
    "# Testing type",
    "expect_type(\n  vec_5,\n  type = \"list\")",
    "# Testing values",
    "expect_equal(\n  vec_5[[\"a\"]],\n  list(10, 2, 4))",
    "expect_equal(\n  vec_5[[\"b\"]],\n  list(20, 1, 3))",
    "expect_equal(\n  vec_5[[\"c\"]],\n  list(2, 3, 30))",
    "# Testing names",
    "expect_equal(\n  names(vec_5),\n  c(\"a\", \"b\", \"c\"),\n  fixed = TRUE)",
    "# Testing length",
    "expect_equal(\n  length(vec_5),\n  3L)",
    "# Testing sum of element lengths",
    "expect_equal(\n  sum(unlist(lapply(vec_5, length))),\n  9L)",
    "# Testing element classes",
    "expect_equal(\n  unlist(lapply(vec_5, class), use.names = FALSE),\n  c(\"list\", \"list\", \"list\"),\n  fixed = TRUE)",
    "# Testing element types",
    "expect_equal(\n  unlist(lapply(vec_5, typeof), use.names = FALSE),\n  c(\"list\", \"list\", \"list\"),\n  fixed = TRUE)",
    "## Finished testing 'vec_5'                                                 ####"
  )

  expect_equal(
    create_expectations_vector(vec_5),
    exp_vec_5
  )
  eval_expectations(exp_vec_5, current_envir)

  # vec_6 (Not all elements are named)
  exp_vec_6 <- list(
    "## Testing 'vec_6'                                                          ####\n## Initially generated by xpectr",
    "# Testing class",
    "expect_equal(\n  class(vec_6),\n  \"list\",\n  fixed = TRUE)",
    "# Testing type",
    "expect_type(\n  vec_6,\n  type = \"list\")",
    "# Testing values",
    "expect_equal(\n  vec_6,\n  list(a = list(10, 2, 4), b = list(20, 1, 3), list(2, 3, 30)))",
    "# Testing names",
    "expect_equal(\n  names(vec_6),\n  c(\"a\", \"b\", \"\"),\n  fixed = TRUE)",
    "# Testing length",
    "expect_equal(\n  length(vec_6),\n  3L)",
    "# Testing sum of element lengths",
    "expect_equal(\n  sum(unlist(lapply(vec_6, length))),\n  9L)",
    "## Finished testing 'vec_6'                                                 ####"
  )

  expect_equal(
    create_expectations_vector(vec_6),
    exp_vec_6
  )
  eval_expectations(exp_vec_6, current_envir)

  # vec_7

  exp_vec_7 <- list(
    "## Testing 'vec_7'                                                          ####\n## Initially generated by xpectr",
    "# Testing class",
    "expect_equal(\n  class(vec_7),\n  \"list\",\n  fixed = TRUE)",
    "# Testing type",
    "expect_type(\n  vec_7,\n  type = \"list\")",
    "# Testing values",
    "expect_equal(\n  vec_7,\n  list(5, 6, 7, 8))",
    "# Testing names",
    "expect_equal(\n  names(vec_7),\n  NULL,\n  fixed = TRUE)",
    "# Testing length",
    "expect_equal(\n  length(vec_7),\n  4L)",
    "# Testing sum of element lengths",
    "expect_equal(\n  sum(unlist(lapply(vec_7, length))),\n  4L)",
    "## Finished testing 'vec_7'                                                 ####"
  )

  expect_equal(
    create_expectations_vector(vec_7),
    exp_vec_7
  )
  eval_expectations(exp_vec_7, current_envir)
})

test_that("expectations are created returned by insertExpectationsAddin()", {

  error_fn <- function() {
    warning("hehe")
    message("hihi")
    stop("STOP NOW!")
  }

  expect_equal(
    insertExpectationsAddin("error_fn()", insert = FALSE),
    list(
      paste0("## Testing 'error_fn()'                                    ",
             "                 ####\n## Initially generated by xpectr"),
      "# Testing side effects",
      paste0("expect_error(\n  xpectr::strip_msg(error_fn()),\n  xpectr::",
             "strip(\"STOP NOW!\"),\n  fixed = TRUE)"),
      "## Finished testing 'error_fn()'                                            ####"
    ),
    fixed = TRUE)

  msgs_warns_fn <- function() {
    warning("hehe")
    message("hihi")
    warning("ohhh")
    message("ihhh")
  }

  expect_equal(
    insertExpectationsAddin("msgs_warns_fn()", insert = FALSE),
    list(
      paste0("## Testing 'msgs_warns_fn()'                               ",
             "                 ####\n## Initially generated by xpectr"),
      "# Testing side effects",
      "expect_warning(\n  xpectr::strip_msg(msgs_warns_fn()),\n  xpectr::strip(\"hehe\"),\n  fixed = TRUE)",
      "expect_warning(\n  xpectr::strip_msg(msgs_warns_fn()),\n  xpectr::strip(\"ohhh\"),\n  fixed = TRUE)",
      "expect_message(\n  xpectr::strip_msg(msgs_warns_fn()),\n  xpectr::strip(\"hihi\\n\"),\n  fixed = TRUE)",
      "expect_message(\n  xpectr::strip_msg(msgs_warns_fn()),\n  xpectr::strip(\"ihhh\\n\"),\n  fixed = TRUE)",
      "## Finished testing 'msgs_warns_fn()'                                       ####"
    ),
    fixed = TRUE)

  expect_equal(
    gxs_selection("msgs_warns_fn()", out = "return", strip = FALSE),
    list("## Testing 'msgs_warns_fn()'                                                ####\n## Initially generated by xpectr",
    "# Testing side effects", "expect_warning(\n  msgs_warns_fn(),\n  \"hehe\",\n  fixed = TRUE)",
    "expect_warning(\n  msgs_warns_fn(),\n  \"ohhh\",\n  fixed = TRUE)",
    "expect_message(\n  msgs_warns_fn(),\n  \"hihi\\n\",\n  fixed = TRUE)",
    "expect_message(\n  msgs_warns_fn(),\n  \"ihhh\\n\",\n  fixed = TRUE)",
    "## Finished testing 'msgs_warns_fn()'                                       ####"),
    fixed = TRUE)

  set_test_seed(42)
  long_df <- data.frame("a" = runif(40), "b" = runif(40), stringsAsFactors = FALSE)

  # Check smpl is used
  expect_equal(
    gxs_selection("long_df", out = "return", strip = FALSE),
    list(
      "## Testing 'long_df'                                                        ####\n## Initially generated by xpectr",
      "# Testing class",
      "expect_equal(\n  class(long_df),\n  \"data.frame\",\n  fixed = TRUE)",
      "# Testing column values",
      paste0("expect_equal(\n  xpectr::smpl(long_df[[\"a\"]], n = 30),\n ",
             " c(0.937075413297862, 0.286139534786344, 0.641745518893003, ",
             "0.519095949130133, 0.736588314641267, 0.13466659723781, 0.70",
             "5064784036949, 0.45774177624844, 0.719112251652405, 0.934672",
             "247152776, 0.255428824340925, 0.978226428385824, 0.117487361",
             "654639, 0.474997081561014, 0.904031387297437, 0.138710167724",
             "639, 0.988891728920862, 0.946668232558295, 0.082437558099627",
             "5, 0.514211784349754, 0.390203467104584, 0.446969628101215, ",
             "0.836004259996116, 0.737595617771149, 0.811055141268298, 0.0",
             "0394833879545331, 0.832916080253199, 0.00733414688147604, 0.",
             "207658972823992, 0.611778643447906),\n  tolerance = 1e-4)"),
      paste0("expect_equal(\n  xpectr::smpl(long_df[[\"b\"]], n = 30),\n ",
             " c(0.435771584976465, 0.0374310328625143, 0.431751248892397,",
             " 0.957576596643776, 0.887754905503243, 0.639978769468144, 0.",
             "618838207330555, 0.333427211269736, 0.346748248208314, 0.398",
             "48541142419, 0.784692775690928, 0.67727683018893, 0.17126433",
             "0390841, 0.261087963823229, 0.67560727451928, 0.982817197917",
             "029, 0.759544267551973, 0.566488424083218, 0.849689718568698",
             ", 0.18947393540293, 0.271286614704877, 0.693204820388928, 0.",
             "240544739644974, 0.0429887960199267, 0.140479094116017, 0.19",
             "7410342283547, 0.719355837674811, 0.00788473873399198, 0.375",
             "489964615554, 0.00157055421732366),\n  tolerance = 1e-4)"),
      "# Testing column names",
      "expect_equal(\n  names(long_df),\n  c(\"a\", \"b\"),\n  fixed = TRUE)",
      "# Testing column classes",
      "expect_equal(\n  unlist(lapply(long_df, class), use.names = FALSE),\n  c(\"numeric\", \"numeric\"),\n  fixed = TRUE)",
      "# Testing column types",
      "expect_equal(\n  unlist(lapply(long_df, typeof), use.names = FALSE),\n  c(\"double\", \"double\"),\n  fixed = TRUE)",
      "# Testing dimensions",
      "expect_equal(\n  dim(long_df),\n  c(40L, 2L))",
      "# Testing group keys",
      "expect_equal(\n  colnames(dplyr::group_keys(long_df)),\n  character(0),\n  fixed = TRUE)",
      "## Finished testing 'long_df'                                               ####"
    ),
    fixed = TRUE)

})

test_that("capture_side_effects() works", {

  # error
  error_fn <- function() {
    message("hey")
    warning("you don't see me")
    stop("lols I'm an error")
  }

  err_sfx <- capture_side_effects(error_fn)
  expect_equal(err_sfx$error, "lols I'm an error", fixed = TRUE)
  expect_null(err_sfx$warnings)
  expect_null(err_sfx$messages)
  expect_true(err_sfx$has_side_effects)

  msgs_warns_fn <- function() {
    message("hey")
    warning("you see me??")
    message("hey again")
    warning("here I aaam!!")
  }

  warn_sfx <- capture_side_effects(fn = msgs_warns_fn)
  expect_null(warn_sfx$error)
  expect_equal(warn_sfx$warnings,
               c("you see me??", "here I aaam!!"),
               fixed = TRUE)
  expect_equal(warn_sfx$messages,
               c("hey\n", "hey again\n"),
               fixed = TRUE)
  expect_true(warn_sfx$has_side_effects)
})


