library(xpectr)
context("gxs_selection()")

test_that("data frame expectations are created properly with gxs_selection()", {

  set_test_seed(1)
  df1 <- tibble::tibble("a" = c(1, 2, 3, 4), "b" = c("a", "f", "g", "s"))

  ## Testing 'gxs_selection("df1", out = "return")'                         ####
  ## Initially generated by xpectr
  # Assigning output
  output_12654 <- gxs_selection("df1", out = "return")
  # Testing class
  expect_equal(
    class(output_12654),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_12654,
    type = "list")
  # Testing values
  expect_equal(
    output_12654,
    list("## Testing 'df1'                                                            ####\n## Initially generated by xpectr",
          "# Testing class", "expect_equal(\n  class(df1),\n  c(\"tbl_df\", \"tbl\", \"data.frame\"),\n  fixed = TRUE)",
          "# Testing column values", "expect_equal(\n  df1[[\"a\"]],\n  c(1, 2, 3, 4),\n  tolerance = 1e-4)",
          "expect_equal(\n  df1[[\"b\"]],\n  c(\"a\", \"f\", \"g\", \"s\"),\n  fixed = TRUE)",
          "# Testing column names", "expect_equal(\n  names(df1),\n  c(\"a\", \"b\"),\n  fixed = TRUE)",
          "# Testing column classes", "expect_equal(\n  xpectr::element_classes(df1),\n  c(\"numeric\", \"character\"),\n  fixed = TRUE)",
          "# Testing column types", "expect_equal(\n  xpectr::element_types(df1),\n  c(\"double\", \"character\"),\n  fixed = TRUE)",
          "# Testing dimensions", "expect_equal(\n  dim(df1),\n  c(4L, 2L))",
          "# Testing group keys", "expect_equal(\n  colnames(dplyr::group_keys(df1)),\n  character(0),\n  fixed = TRUE)",
          "## Finished testing 'df1'                                                   ####"))
  # Testing names
  expect_equal(
    names(output_12654),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_12654),
    17L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_12654)),
    17L)
  ## Finished testing 'gxs_selection("df1", out = "return")'                ####

  ## Testing 'gxs_selection("tibble::tibble('a' = c(1, 2, ...'              ####
  ## Initially generated by xpectr
  # Assigning output
  output_18982 <- gxs_selection("tibble::tibble('a' = c(1, 2, 3, 4), 'b' = c('b', 'f', 'g', 's'))", out = "return")
  # Testing class
  expect_equal(
    class(output_18982),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_18982,
    type = "list")
  # Testing values
  expect_equal(
    output_18982,
    list("## Testing 'tibble::tibble('a' = c(1, 2, 3, 4), 'b' = c('b...'              ####\n## Initially generated by xpectr",
          "# Assigning output", "output_12654 <- tibble::tibble('a' = c(1, 2, 3, 4), 'b' = c('b', 'f', 'g', 's'))",
          "# Testing class", "expect_equal(\n  class(output_12654),\n  c(\"tbl_df\", \"tbl\", \"data.frame\"),\n  fixed = TRUE)",
          "# Testing column values", "expect_equal(\n  output_12654[[\"a\"]],\n  c(1, 2, 3, 4),\n  tolerance = 1e-4)",
          "expect_equal(\n  output_12654[[\"b\"]],\n  c(\"b\", \"f\", \"g\", \"s\"),\n  fixed = TRUE)",
          "# Testing column names", "expect_equal(\n  names(output_12654),\n  c(\"a\", \"b\"),\n  fixed = TRUE)",
          "# Testing column classes", "expect_equal(\n  xpectr::element_classes(output_12654),\n  c(\"numeric\", \"character\"),\n  fixed = TRUE)",
          "# Testing column types", "expect_equal(\n  xpectr::element_types(output_12654),\n  c(\"double\", \"character\"),\n  fixed = TRUE)",
          "# Testing dimensions", "expect_equal(\n  dim(output_12654),\n  c(4L, 2L))",
          "# Testing group keys", "expect_equal(\n  colnames(dplyr::group_keys(output_12654)),\n  character(0),\n  fixed = TRUE)",
          "## Finished testing 'tibble::tibble('a' = c(1, 2, 3, 4), 'b' = c('b...'     ####"))
  # Testing names
  expect_equal(
    names(output_18982),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_18982),
    19L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_18982)),
    19L)
  ## Finished testing 'gxs_selection("tibble::tibble('a' = c(1, 2, ...'     ####

  df1$c <- list(list(1, 2, 3), list(2, 3, 4, 5), list(2, 3, 7, 21, 2), list(2))


  ## Testing 'gxs_selection("df1", out = "return")'                         ####
  ## Initially generated by xpectr
  # Testing side effects
  expect_warning(
    xpectr::strip_msg(gxs_selection("df1", out = "return")),
    xpectr::strip("Skipped column c."),
    fixed = TRUE)
  ## Finished testing 'gxs_selection("df1", out = "return")'                ####


})

test_that("list of lists expectations are created properly with gxs_selection()", {

  l <- list(list(1, 2, 3), list(2, 3, 4, list(5, 3)), list(2, 3, 7, 21, 2), list(2))

  ## Testing 'gxs_selection("l", out = "return")'                           ####
  ## Initially generated by xpectr
  # Assigning output
  output_19483 <- gxs_selection("l", out = "return")
  # Testing class
  expect_equal(
    class(output_19483),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_19483,
    type = "list")
  # Testing values
  expect_equal(
    output_19483,
    list("## Testing 'l'                                                              ####\n## Initially generated by xpectr",
          "# Testing class", "expect_equal(\n  class(l),\n  \"list\",\n  fixed = TRUE)",
          "# Testing type", "expect_type(\n  l,\n  type = \"list\")",
          "# Testing values", "expect_equal(\n  l,\n  list(list(1, 2, 3), list(2, 3, 4, list(5, 3)), list(2, 3, 7, 21,\n    2), list(2)))",
          "# Testing names", "expect_equal(\n  names(l),\n  NULL,\n  fixed = TRUE)",
          "# Testing length", "expect_equal(\n  length(l),\n  4L)",
          "# Testing sum of element lengths", "expect_equal(\n  sum(xpectr::element_lengths(l)),\n  13L)",
          "## Finished testing 'l'                                                     ####"))
  # Testing names
  expect_equal(
    names(output_19483),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_19483),
    14L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_19483)),
    14L)
  ## Finished testing 'gxs_selection("l", out = "return")'                  ####

})

test_that("vector expectations are created properly with gxs_selection()", {

  vec_1 <- c(1,2,3,4,5,6,NA)

  ## Testing 'gxs_selection("vec_1", out = "return")'                       ####
  ## Initially generated by xpectr
  # Assigning output
  output_13720 <- gxs_selection("vec_1", out = "return")
  # Testing class
  expect_equal(
    class(output_13720),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_13720,
    type = "list")
  # Testing values
  expect_equal(
    output_13720,
    list(
      "## Testing 'vec_1'                                                          ####\n## Initially generated by xpectr",
      "# Testing class",
      "expect_equal(\n  class(vec_1),\n  \"numeric\",\n  fixed = TRUE)",
      "# Testing type",
      "expect_type(\n  vec_1,\n  type = \"double\")",
      "# Testing values",
      "expect_equal(\n  vec_1,\n  c(1, 2, 3, 4, 5, 6, NA),\n  tolerance = 1e-4)",
      "# Testing names",
      "expect_equal(\n  names(vec_1),\n  NULL,\n  fixed = TRUE)",
      "# Testing length",
      "expect_equal(\n  length(vec_1),\n  7L)",
      "# Testing sum of element lengths",
      "expect_equal(\n  sum(xpectr::element_lengths(vec_1)),\n  7L)",
      "## Finished testing 'vec_1'                                                 ####"
    ))
  # Testing names
  expect_equal(
    names(output_13720),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_13720),
    14L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_13720)),
    14L)
  ## Finished testing 'gxs_selection("vec_1", out = "return")'              ####

})

test_that("factor expectations are created properly with gxs_selection()", {

  fact_1 <- factor(as.character(c(1,2,3,4,5,6,NA)))

  ## Testing 'gxs_selection("fact_1", out = "return")'                      ####
  ## Initially generated by xpectr
  # Assigning output
  output_15727 <- gxs_selection("fact_1", out = "return")
  # Testing class
  expect_equal(
    class(output_15727),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_15727,
    type = "character")
  # Testing values
  expect_equal(
    output_15727,
    c(
      "## Testing 'fact_1'                                                         ####\n## Initially generated by xpectr",
      "# Testing is factor",
      "expect_true(\n  is.factor(fact_1))",
      "# Testing values",
      "expect_equal(\n  as.character(fact_1),\n  c(\"1\", \"2\", \"3\", \"4\", \"5\", \"6\", NA),\n  fixed = TRUE)",
      "# Testing names",
      "expect_equal(\n  names(fact_1),\n  NULL,\n  fixed = TRUE)",
      "# Testing length",
      "expect_equal(\n  length(fact_1),\n  7L)",
      "# Testing number of levels",
      "expect_equal(\n  nlevels(fact_1),\n  6L)",
      "# Testing levels",
      "expect_equal(\n  levels(fact_1),\n  c(\"1\", \"2\", \"3\", \"4\", \"5\", \"6\"),\n  fixed = TRUE)",
      "## Finished testing 'fact_1'                                                ####"
    ),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_15727),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_15727),
    14L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_15727)),
    14L)
  ## Finished testing 'gxs_selection("fact_1", out = "return")'             ####


})

test_that("NULL expectations are created properly with gxs_selection()", {

  ## Testing 'gxs_selection("NULL", out = "return")'                        ####
  ## Initially generated by xpectr
  # Assigning output
  output_14242 <- gxs_selection("NULL", out = "return")
  # Testing class
  expect_equal(
    class(output_14242),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_14242,
    type = "character")
  # Testing values
  expect_equal(
    output_14242,
    c(
      "## Testing 'NULL'                                                           ####\n## Initially generated by xpectr",
      "# Testing is NULL",
      "expect_true(\n  is.null(NULL))",
      "## Finished testing 'NULL'                                                  ####"
    ),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_14242),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_14242),
    4L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_14242)),
    4L)
  ## Finished testing 'gxs_selection("NULL", out = "return")'               ####

})

test_that("NA expectations are created properly with gxs_selection()", {

  ## Testing 'gxs_selection("NA", out = "return")'                          ####
  ## Initially generated by xpectr
  # Assigning output
  output_14817 <- gxs_selection("NA", out = "return")
  # Testing class
  expect_equal(
    class(output_14817),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_14817,
    type = "list")
  # Testing values
  expect_equal(
    output_14817,
    list("## Testing 'NA'                                                             ####\n## Initially generated by xpectr",
          "# Testing class", "expect_equal(\n  class(NA),\n  \"logical\",\n  fixed = TRUE)",
          "# Testing type", "expect_type(\n  NA,\n  type = \"logical\")",
          "# Testing values", "expect_equal(\n  NA,\n  NA)", "# Testing names",
          "expect_equal(\n  names(NA),\n  NULL,\n  fixed = TRUE)", "# Testing length",
          "expect_equal(\n  length(NA),\n  1L)", "# Testing sum of element lengths",
          "expect_equal(\n  sum(xpectr::element_lengths(NA)),\n  1L)",
          "## Finished testing 'NA'                                                    ####"))
  # Testing names
  expect_equal(
    names(output_14817),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_14817),
    14L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_14817)),
    14L)
  ## Finished testing 'gxs_selection("NA", out = "return")'                 ####

})

test_that("single number expectations are created properly with gxs_selection()", {

  ## Testing 'gxs_selection("1", out = "return")'                           ####
  ## Initially generated by xpectr
  # Assigning output
  output_17871 <- gxs_selection("1", out = "return")
  # Testing class
  expect_equal(
    class(output_17871),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_17871,
    type = "list")
  # Testing values
  expect_equal(
    output_17871,
    list("## Testing '1'                                                              ####\n## Initially generated by xpectr",
          "# Testing class", "expect_equal(\n  class(1),\n  \"numeric\",\n  fixed = TRUE)",
          "# Testing type", "expect_type(\n  1,\n  type = \"double\")",
          "# Testing values", "expect_equal(\n  1,\n  1,\n  tolerance = 1e-4)",
          "# Testing names", "expect_equal(\n  names(1),\n  NULL,\n  fixed = TRUE)",
          "# Testing length", "expect_equal(\n  length(1),\n  1L)",
          "# Testing sum of element lengths", "expect_equal(\n  sum(xpectr::element_lengths(1)),\n  1L)",
          "## Finished testing '1'                                                     ####"))
  # Testing names
  expect_equal(
    names(output_17871),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_17871),
    14L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_17871)),
    14L)
  ## Finished testing 'gxs_selection("1", out = "return")'                  ####

})

test_that("missing variable expectations are created properly with gxs_selection()", {

  ## Testing 'gxs_selection("MISSINGVAR", out = "return")'                  ####
  ## Initially generated by xpectr
  # Assigning output
  output_11242 <- gxs_selection("MISSINGVAR", out = "return")
  # Testing class
  expect_equal(
    class(output_11242),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_11242,
    type = "list")
  # Testing values
  expect_equal(
    output_11242,
    list(
      "## Testing 'MISSINGVAR'                                                     ####\n## Initially generated by xpectr",
      "# Testing side effects",
      "expect_error(\n  xpectr::strip_msg(MISSINGVAR),\n  xpectr::strip(\"object 'MISSINGVAR' not found\"),\n  fixed = TRUE)",
      "## Finished testing 'MISSINGVAR'                                            ####"
    ))
  # Testing names
  expect_equal(
    names(output_11242),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_11242),
    4L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_11242)),
    4L)
  ## Finished testing 'gxs_selection("MISSINGVAR", out = "return")'         ####

})

test_that("function object expectations are created properly with gxs_selection()", {

  f1 <- function(a = "x", b = NULL, c = NA, d){
    paste0(a, b, c, d)
  }

  f2 <- function(){
    NULL
  }

  f3 <- function(x1,x2,x3){
    x1 + x2 + x3
  }

  f4 <- function(x1 = message, x2 = warning, x3 = stop){x1("m"); x2("w"); x3("e")}

  ## Testing 'gxs_selection("f1", out = "return")'                          ####
  ## Initially generated by xpectr
  # Assigning output
  output_13431 <- gxs_selection("f1", out = "return")
  # Testing class
  expect_equal(
    class(output_13431),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_13431,
    type = "character")
  # Testing values
  expect_equal(
    output_13431,
    c(
      "## Testing 'f1'                                                             ####\n## Initially generated by xpectr",
      "# Testing is function",
      "expect_true(\n  is.function(f1))",
      "# Testing argument names and default values",
      "expect_equal(\n  xpectr::simplified_formals(f1),\n  c(\"a = \\\"x\\\"\", \"b = NULL\", \"c = NA\", \"d\"),\n  fixed = TRUE)",
      "# Testing function definition",
      "expect_equal(\n  deparse(f1),\n  c(\"function (a = \\\"x\\\", b = NULL, c = NA, d) \", \"{\", \"    paste0(a, b, c, d)\", \n        \"}\"),\n  fixed = TRUE)",
      "## Finished testing 'f1'                                                    ####"
    ),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_13431),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_13431),
    8L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_13431)),
    8L)
  ## Finished testing 'gxs_selection("f1", out = "return")'                 ####

  ## Testing 'gxs_selection("f2", out = "return")'                          ####
  ## Initially generated by xpectr
  # Assigning output
  output_17225 <- gxs_selection("f2", out = "return")
  # Testing class
  expect_equal(
    class(output_17225),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_17225,
    type = "character")
  # Testing values
  expect_equal(
    output_17225,
    c(
      "## Testing 'f2'                                                             ####\n## Initially generated by xpectr",
      "# Testing is function",
      "expect_true(\n  is.function(f2))",
      "# Testing argument names and default values",
      "expect_equal(\n  xpectr::simplified_formals(f2),\n  NULL,\n  fixed = TRUE)",
      "# Testing function definition",
      "expect_equal(\n  deparse(f2),\n  c(\"function () \", \"{\", \"    NULL\", \"}\"),\n  fixed = TRUE)",
      "## Finished testing 'f2'                                                    ####"
    ),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_17225),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_17225),
    8L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_17225)),
    8L)
  ## Finished testing 'gxs_selection("f2", out = "return")'                 ####

  ## Testing 'gxs_selection("f3", out = "return")'                          ####
  ## Initially generated by xpectr
  # Assigning output
  output_11362 <- gxs_selection("f3", out = "return")
  # Testing class
  expect_equal(
    class(output_11362),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_11362,
    type = "character")
  # Testing values
  expect_equal(
    output_11362,
    c(
      "## Testing 'f3'                                                             ####\n## Initially generated by xpectr",
      "# Testing is function",
      "expect_true(\n  is.function(f3))",
      "# Testing argument names and default values",
      "expect_equal(\n  xpectr::simplified_formals(f3),\n  c(\"x1\", \"x2\", \"x3\"),\n  fixed = TRUE)",
      "# Testing function definition",
      "expect_equal(\n  deparse(f3),\n  c(\"function (x1, x2, x3) \", \"{\", \"    x1 + x2 + x3\", \"}\"),\n  fixed = TRUE)",
      "## Finished testing 'f3'                                                    ####"
    ),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_11362),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_11362),
    8L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_11362)),
    8L)
  ## Finished testing 'gxs_selection("f3", out = "return")'                 ####

  ## Testing 'gxs_selection("f4", out = "return")'                          ####
  ## Initially generated by xpectr
  # Assigning output
  output_12105 <- gxs_selection("f4", out = "return")
  # Testing class
  expect_equal(
    class(output_12105),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_12105,
    type = "character")
  # Testing values
  expect_equal(
    output_12105,
    c(
      "## Testing 'f4'                                                             ####\n## Initially generated by xpectr",
      "# Testing is function",
      "expect_true(\n  is.function(f4))",
      "# Testing argument names and default values",
      "expect_equal(\n  xpectr::simplified_formals(f4),\n  c(\"x1 = message\", \"x2 = warning\", \"x3 = stop\"),\n  fixed = TRUE)",
      "# Testing function definition",
      "expect_equal(\n  deparse(f4),\n  c(\"function (x1 = message, x2 = warning, x3 = stop) \", \"{\", \"    x1(\\\"m\\\")\", \n        \"    x2(\\\"w\\\")\", \"    x3(\\\"e\\\")\", \"}\"),\n  fixed = TRUE)",
      "## Finished testing 'f4'                                                    ####"
    ),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_12105),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_12105),
    8L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_12105)),
    8L)
  ## Finished testing 'gxs_selection("f4", out = "return")'                 ####

  # gxs_selection("f4")
  ## Testing 'f4'                                                             ####
  ## Initially generated by xpectr
  # Testing is function
  expect_true(
    is.function(f4))
  # Testing argument names and default values
  expect_equal(
    xpectr::simplified_formals(f4),
    c("x1 = message", "x2 = warning", "x3 = stop"),
    fixed = TRUE)
  # Testing function definition
  expect_equal(
    deparse(f4),
    c(
      "function (x1 = message, x2 = warning, x3 = stop) ",
      "{",
      "    x1(\"m\")",
      "    x2(\"w\")",
      "    x3(\"e\")",
      "}"
    ),
    fixed = TRUE)
  ## Finished testing 'f4'                                                    ####


})

test_that("formula expectations are created properly with gxs_selection()", {

  f <- as.formula("e + f * x ~ y + b + d + log(u)")

  ## Testing 'gxs_selection("f", out = "return")'                           ####
  ## Initially generated by xpectr
  # Assigning output
  output_15735 <- gxs_selection("f", out = "return")
  # Testing class
  expect_equal(
    class(output_15735),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_15735,
    type = "character")
  # Testing values
  expect_equal(
    output_15735,
    c(
      "## Testing 'f'                                                              ####\n## Initially generated by xpectr",
      "# Testing is formula",
      "expect_true(\n  rlang::is_formula(f))",
      "# Testing formula",
      "expect_equal(\n  f,\n  e + f * x ~ y + b + d + log(u))",
      "## Finished testing 'f'                                                     ####"
    ),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_15735),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_15735),
    6L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_15735)),
    6L)
  ## Finished testing 'gxs_selection("f", out = "return")'                  ####

  ## Testing 'f'                                                              ####
  ## Initially generated by xpectr
  # Testing is formula
  expect_true(
    rlang::is_formula(f))
  # Testing formula
  expect_equal(
    f,
    e + f * x ~ y + b + d + log(u))
  ## Finished testing 'f'                                                     ####

  set_test_seed(1)
  # gxs_selection("t ~ 1 + y + (1| love)", out = "return")
  ## Testing 'gxs_selection("t ~ 1 + y + (1| love)", out =...'              ####
  ## Initially generated by xpectr
  # Assigning output
  output_13720 <- gxs_selection("t ~ 1 + y + (1| love)", out = "return")
  # Testing class
  expect_equal(
    class(output_13720),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_13720,
    type = "character")
  # Testing values
  expect_equal(
    output_13720,
    c(
      "## Testing 't ~ 1 + y + (1| love)'                                          ####\n## Initially generated by xpectr",
      "# Assigning output",
      "output_12654 <- t ~ 1 + y + (1| love)",
      "# Testing is formula",
      "expect_true(\n  rlang::is_formula(output_12654))",
      "# Testing formula",
      "expect_equal(\n  output_12654,\n  t ~ 1 + y + (1 | love))",
      "## Finished testing 't ~ 1 + y + (1| love)'                                 ####"
    ),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_13720),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_13720),
    8L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_13720)),
    8L)
  ## Finished testing 'gxs_selection("t ~ 1 + y + (1| love)", out =...'     ####


  ## Testing 't ~ 1 + y + (1| love)'                                          ####
  ## Initially generated by xpectr
  # Testing is formula
  expect_true(rlang::is_formula(t ~ 1 + y + (1 | love)))
  # Testing formula
  expect_equal(t ~ 1 + y + (1| love),
               t ~ 1 + y + (1 | love))
  ## Finished testing 't ~ 1 + y + (1| love)'                                 ####


  f_fn <- function(){as.formula("e + f * x ~ y + b + d + log(u)")}

  set_test_seed(1)
  ## Testing 'gxs_selection("f_fn()", out = "return")'                      ####
  ## Initially generated by xpectr
  # Assigning output
  output_13720 <- gxs_selection("f_fn()", out = "return")
  # Testing class
  expect_equal(
    class(output_13720),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_13720,
    type = "character")
  # Testing values
  expect_equal(
    output_13720,
    c("## Testing 'f_fn()'                                                         ####\n## Initially generated by xpectr",
          "# Assigning output", "output_12654 <- f_fn()", "# Testing is formula",
          "expect_true(\n  rlang::is_formula(output_12654))", "# Testing formula",
          "expect_equal(\n  output_12654,\n  e + f * x ~ y + b + d + log(u))",
          "## Finished testing 'f_fn()'                                                ####"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_13720),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_13720),
    8L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_13720)),
    8L)
  ## Finished testing 'gxs_selection("f_fn()", out = "return")'             ####

  ## Testing 'f_fn()'                                                       ####
  ## Initially generated by xpectr
  # Assigning output
  output_12654 <- f_fn()
  # Testing is formula
  expect_true(
    rlang::is_formula(output_12654))
  # Testing formula
  expect_equal(
    output_12654,
    e + f * x ~ y + b + d + log(u))
  ## Finished testing 'f_fn()'                                              ####

})

test_that("matrix expectations are created properly with gxs_selection()", {

  set_test_seed(1)
  m_num <- matrix(runif(12), 4, 3)
  m_char <- matrix(as.character(runif(12)), 3, 4)
  m_symm <- matrix(1, 3, 3)

  set_test_seed(1)
  ## Testing 'gxs_selection("matrix(runif(12), 4, 3)", out...'              ####
  ## Initially generated by xpectr
  # Assigning output
  output_13840 <- gxs_selection("matrix(runif(12), 4, 3)", out = "return")
  # Testing class
  expect_equal(
    class(output_13840),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_13840,
    type = "list")
  # Testing values
  expect_equal(
    output_13840,
    list("## Testing 'matrix(runif(12), 4, 3)'                                        ####\n## Initially generated by xpectr",
          "# Assigning output", "output_16869 <- matrix(runif(12), 4, 3)",
          "# Testing class", "expect_equal(\n  class(output_16869),\n  \"matrix\",\n  fixed = TRUE)",
          "# Testing type", "expect_type(\n  output_16869,\n  type = \"double\")",
          "# Testing column values", "expect_equal(\n  output_16869[, 1],\n  c(0.26551, 0.37212, 0.57285, 0.90821),\n  tolerance = 1e-4)",
          "expect_equal(\n  output_16869[, 2],\n  c(0.20168, 0.89839, 0.94468, 0.6608),\n  tolerance = 1e-4)",
          "expect_equal(\n  output_16869[, 3],\n  c(0.62911, 0.06179, 0.20597, 0.17656),\n  tolerance = 1e-4)",
          "# Testing column names", "expect_equal(\n  colnames(output_16869),\n  NULL,\n  fixed = TRUE)",
          "# Testing row names", "expect_equal(\n  rownames(output_16869),\n  NULL,\n  fixed = TRUE)",
          "# Testing dimensions", "expect_equal(\n  dim(output_16869),\n  4:3)",
          "# Testing symmetry", "expect_true(\n  !isSymmetric(output_16869))",
          "## Finished testing 'matrix(runif(12), 4, 3)'                               ####"))
  # Testing names
  expect_equal(
    names(output_13840),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_13840),
    20L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_13840)),
    20L)
  ## Finished testing 'gxs_selection("matrix(runif(12), 4, 3)", out...'     ####

  set_test_seed(1)
  # gxs_selection("matrix(runif(12), 4, 3)")
  ## Testing 'matrix(runif(12), 4, 3)'                                        ####
  ## Initially generated by xpectr
  # Assigning output
  output_16869 <- matrix(runif(12), 4, 3)
  # Testing class
  expect_equal(
    class(output_16869),
    "matrix",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_16869,
    type = "double")
  # Testing column values
  expect_equal(
    output_16869[, 1],
    c(0.26551, 0.37212, 0.57285, 0.90821),
    tolerance = 1e-4)
  expect_equal(
    output_16869[, 2],
    c(0.20168, 0.89839, 0.94468, 0.6608),
    tolerance = 1e-4)
  expect_equal(
    output_16869[, 3],
    c(0.62911, 0.06179, 0.20597, 0.17656),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    colnames(output_16869),
    NULL,
    fixed = TRUE)
  # Testing row names
  expect_equal(
    rownames(output_16869),
    NULL,
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_16869),
    4:3)
  # Testing symmetry
  expect_true(
    !isSymmetric(output_16869))
  ## Finished testing 'matrix(runif(12), 4, 3)'                               ####

  set_test_seed(1)
  ## Testing 'gxs_selection("m_num", out = "return")'                       ####
  ## Initially generated by xpectr
  # Assigning output
  output_12654 <- gxs_selection("m_num", out = "return")
  # Testing class
  expect_equal(
    class(output_12654),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_12654,
    type = "list")
  # Testing values
  expect_equal(
    output_12654,
    list("## Testing 'm_num'                                                          ####\n## Initially generated by xpectr",
          "# Testing class", "expect_equal(\n  class(m_num),\n  \"matrix\",\n  fixed = TRUE)",
          "# Testing type", "expect_type(\n  m_num,\n  type = \"double\")",
          "# Testing column values", "expect_equal(\n  m_num[, 1],\n  c(0.26551, 0.37212, 0.57285, 0.90821),\n  tolerance = 1e-4)",
          "expect_equal(\n  m_num[, 2],\n  c(0.20168, 0.89839, 0.94468, 0.6608),\n  tolerance = 1e-4)",
          "expect_equal(\n  m_num[, 3],\n  c(0.62911, 0.06179, 0.20597, 0.17656),\n  tolerance = 1e-4)",
          "# Testing column names", "expect_equal(\n  colnames(m_num),\n  NULL,\n  fixed = TRUE)",
          "# Testing row names", "expect_equal(\n  rownames(m_num),\n  NULL,\n  fixed = TRUE)",
          "# Testing dimensions", "expect_equal(\n  dim(m_num),\n  4:3)",
          "# Testing symmetry", "expect_true(\n  !isSymmetric(m_num))",
          "## Finished testing 'm_num'                                                 ####"))
  # Testing names
  expect_equal(
    names(output_12654),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_12654),
    18L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_12654)),
    18L)
  ## Finished testing 'gxs_selection("m_num", out = "return")'              ####

  set_test_seed(1)
  # gxs_selection("m_num")
  ## Testing 'm_num'                                                          ####
  ## Initially generated by xpectr
  # Testing class
  expect_equal(
    class(m_num),
    "matrix",
    fixed = TRUE)
  # Testing type
  expect_type(
    m_num,
    type = "double")
  # Testing column values
  expect_equal(
    m_num[, 1],
    c(0.26551, 0.37212, 0.57285, 0.90821),
    tolerance = 1e-4)
  expect_equal(
    m_num[, 2],
    c(0.20168, 0.89839, 0.94468, 0.6608),
    tolerance = 1e-4)
  expect_equal(
    m_num[, 3],
    c(0.62911, 0.06179, 0.20597, 0.17656),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    colnames(m_num),
    NULL,
    fixed = TRUE)
  # Testing row names
  expect_equal(
    rownames(m_num),
    NULL,
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(m_num),
    4:3)
  # Testing symmetry
  expect_true(
    !isSymmetric(m_num))
  ## Finished testing 'm_num'                                                 ####

  set_test_seed(1)
  ## Testing 'gxs_selection("m_char", out = "return")'                      ####
  ## Initially generated by xpectr
  # Assigning output
  output_12654 <- gxs_selection("m_char", out = "return")
  # Testing class
  expect_equal(
    class(output_12654),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_12654,
    type = "list")
  # Testing values
  expect_equal(
    output_12654,
    list("## Testing 'm_char'                                                         ####\n## Initially generated by xpectr",
          "# Testing class", "expect_equal(\n  class(m_char),\n  \"matrix\",\n  fixed = TRUE)",
          "# Testing type", "expect_type(\n  m_char,\n  type = \"character\")",
          "# Testing row values", "expect_equal(\n  m_char[1, ],\n  c(\"0.687022846657783\", \"0.497699242085218\", \"0.380035179434344\", \n        \"0.212142521282658\"),\n  fixed = TRUE)",
          "expect_equal(\n  m_char[2, ],\n  c(\"0.384103718213737\", \"0.717618508264422\", \"0.777445221319795\", \n        \"0.651673766085878\"),\n  fixed = TRUE)",
          "expect_equal(\n  m_char[3, ],\n  c(\"0.769841419998556\", \"0.991906094830483\", \"0.934705231105909\", \n        \"0.125555095961317\"),\n  fixed = TRUE)",
          "# Testing column names", "expect_equal(\n  colnames(m_char),\n  NULL,\n  fixed = TRUE)",
          "# Testing row names", "expect_equal(\n  rownames(m_char),\n  NULL,\n  fixed = TRUE)",
          "# Testing dimensions", "expect_equal(\n  dim(m_char),\n  3:4)",
          "# Testing symmetry", "expect_true(\n  !isSymmetric(m_char))",
          "## Finished testing 'm_char'                                                ####"))
  # Testing names
  expect_equal(
    names(output_12654),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_12654),
    18L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_12654)),
    18L)
  ## Finished testing 'gxs_selection("m_char", out = "return")'             ####

  set_test_seed(1)
  # gxs_selection("m_char")
  ## Testing 'm_char'                                                         ####
  ## Initially generated by xpectr
  # Testing class
  expect_equal(
    class(m_char),
    "matrix",
    fixed = TRUE)
  # Testing type
  expect_type(
    m_char,
    type = "character")
  # Testing row values
  expect_equal(
    m_char[1, ],
    c("0.687022846657783", "0.497699242085218", "0.380035179434344",
          "0.212142521282658"),
    fixed = TRUE)
  expect_equal(
    m_char[2, ],
    c("0.384103718213737", "0.717618508264422", "0.777445221319795",
          "0.651673766085878"),
    fixed = TRUE)
  expect_equal(
    m_char[3, ],
    c("0.769841419998556", "0.991906094830483", "0.934705231105909",
          "0.125555095961317"),
    fixed = TRUE)
  # Testing column names
  expect_equal(
    colnames(m_char),
    NULL,
    fixed = TRUE)
  # Testing row names
  expect_equal(
    rownames(m_char),
    NULL,
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(m_char),
    3:4)
  # Testing symmetry
  expect_true(
    !isSymmetric(m_char))
  ## Finished testing 'm_char'                                                ####

  set_test_seed(1)
  ## Testing 'gxs_selection("m_symm", out = "return")'                      ####
  ## Initially generated by xpectr
  # Assigning output
  output_12654 <- gxs_selection("m_symm", out = "return")
  # Testing class
  expect_equal(
    class(output_12654),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_12654,
    type = "list")
  # Testing values
  expect_equal(
    output_12654,
    list("## Testing 'm_symm'                                                         ####\n## Initially generated by xpectr",
          "# Testing class", "expect_equal(\n  class(m_symm),\n  \"matrix\",\n  fixed = TRUE)",
          "# Testing type", "expect_type(\n  m_symm,\n  type = \"double\")",
          "# Testing column values", "expect_equal(\n  m_symm[, 1],\n  c(1, 1, 1),\n  tolerance = 1e-4)",
          "expect_equal(\n  m_symm[, 2],\n  c(1, 1, 1),\n  tolerance = 1e-4)",
          "expect_equal(\n  m_symm[, 3],\n  c(1, 1, 1),\n  tolerance = 1e-4)",
          "# Testing column names", "expect_equal(\n  colnames(m_symm),\n  NULL,\n  fixed = TRUE)",
          "# Testing row names", "expect_equal(\n  rownames(m_symm),\n  NULL,\n  fixed = TRUE)",
          "# Testing dimensions", "expect_equal(\n  dim(m_symm),\n  c(3L, 3L))",
          "# Testing symmetry", "expect_true(\n  isSymmetric(m_symm))",
          "## Finished testing 'm_symm'                                                ####"))
  # Testing names
  expect_equal(
    names(output_12654),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_12654),
    18L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_12654)),
    18L)
  ## Finished testing 'gxs_selection("m_symm", out = "return")'             ####

  set_test_seed(1)
  # gxs_selection("m_symm")
  ## Testing 'm_symm'                                                         ####
  ## Initially generated by xpectr
  # Testing class
  expect_equal(
    class(m_symm),
    "matrix",
    fixed = TRUE)
  # Testing type
  expect_type(
    m_symm,
    type = "double")
  # Testing column values
  expect_equal(
    m_symm[, 1],
    c(1, 1, 1),
    tolerance = 1e-4)
  expect_equal(
    m_symm[, 2],
    c(1, 1, 1),
    tolerance = 1e-4)
  expect_equal(
    m_symm[, 3],
    c(1, 1, 1),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    colnames(m_symm),
    NULL,
    fixed = TRUE)
  # Testing row names
  expect_equal(
    rownames(m_symm),
    NULL,
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(m_symm),
    c(3L, 3L))
  # Testing symmetry
  expect_true(
    isSymmetric(m_symm))
  ## Finished testing 'm_symm'                                                ####



})
