library(xpectr)
context("gxs_function()")

test_that("gxs_function() works", {

  # Some arbitrary function
  # Have constraints on the arguments
  # and will output slightly different things depending on
  # the values of the args
  fn <- function(a, a_fn, b, d = NULL, e = 3, f = "hi"){

    # Check arguments ####
    assert_collection <- checkmate::makeAssertCollection()
    checkmate::assert_number(x = a, lower = 4, upper = 6, add = assert_collection)
    checkmate::assert_function(x = a_fn, add = assert_collection)
    checkmate::assert_character(x = b, min.chars = 3,
                                any.missing = FALSE,
                                len = 2,
                                add = assert_collection)
    checkmate::assert_data_frame(
      x = d,
      min.rows = 3,
      min.cols = 1,
      col.names = "named",
      null.ok = TRUE,
      add = assert_collection
    )
    checkmate::assert_count(
      x = e,
      positive = TRUE,
      null.ok = TRUE,
      add = assert_collection
    )
    checkmate::assert_string(x = f, min.chars = 2, add = assert_collection)
    checkmate::reportAssertions(assert_collection)
    # End of argument checks ####

    n <- a_fn(a * e)
    m <- paste0(f, ": ", paste0(b, collapse = ", "))

    if (!is.null(d)){
      d[["column"]] <- n
      output <- list("d" = d, "m" = m)
    } else {
      output <- list("n" = n, "m" = m)
    }

    output
  }

  current_envir <- sys.frame(which = sys.nframe())

  # All errors ####
  expected_tests <- c(
    paste0("## Testing 'fn'                                            ",
           "                 ####\n## Initially generated by xpectr"),
    "# Testing different combinations of argument values",
    "# Testing fn(a = 2, a_fn = mean, b = \"ah\")",
    paste0("expect_error(\n  xpectr::strip_msg(fn(a = 2, a_fn = mean, b",
           " = \"ah\")),\n  xpectr::strip(paste0(\"2 assertions failed:",
           "\\n * Variable 'a': Element 0 is not >= 4\",\n         \".\\n",
           " * Variable 'b': Must have length 2, but has length 1.\")),",
           "\n  fixed = TRUE)"),
    "# Testing fn(a = 1, a_fn = sum, b = \"ah\")",
    paste0("expect_error(\n  xpectr::strip_msg(fn(a = 1, a_fn = sum, b ",
           "= \"ah\")),\n  xpectr::strip(paste0(\"2 assertions failed:",
           "\\n * Variable 'a': Element 0 is not >= 4\",\n         \".\\n ",
           "* Variable 'b': Must have length 2, but has length 1.\")),\n",
           "  fixed = TRUE)"),
    "# Testing fn(a = 1, a_fn = mean, b = \"eh\")",
    paste0("expect_error(\n  xpectr::strip_msg(fn(a = 1, a_fn = mean, b",
           " = \"eh\")),\n  xpectr::strip(paste0(\"2 assertions failed:",
           "\\n * Variable 'a': Element 0 is not >= 4\",\n         \".\\n",
           " * Variable 'b': Must have length 2, but has length 1.\")),",
           "\n  fixed = TRUE)"),
    "# Testing fn(a = NULL, a_fn = mean, b = \"ah\")",
    paste0("expect_error(\n  xpectr::strip_msg(fn(a = NULL, a_fn = mean",
           ", b = \"ah\")),\n  xpectr::strip(paste0(\"2 assertions faile",
           "d:\\n * Variable 'a': Must be of type 'numb\",\n         \"e",
           "r', not 'NULL'.\\n * Variable 'b': Must have length 2, but h",
           "\",\n         \"as length 1.\")),\n  fixed = TRUE)"),
    "# Testing fn(a = 1, a_fn = NULL, b = \"ah\")",
    paste0("expect_error(\n  xpectr::strip_msg(fn(a = 1, a_fn = NULL, b",
           " = \"ah\")),\n  xpectr::strip(paste0(\"3 assertions failed:",
           "\\n * Variable 'a': Element 0 is not >= 4\",\n         \".\\n",
           " * Variable 'a_fn': Must be a function, not 'NULL'.\\n * V\"",
           ",\n         \"ariable 'b': Must have length 2, but has lengt",
           "h 1.\")),\n  fixed = TRUE)"),
    "# Testing fn(a = 1, a_fn = mean, b = NULL)",
    paste0("expect_error(\n  xpectr::strip_msg(fn(a = 1, a_fn = mean, b",
           " = NULL)),\n  xpectr::strip(paste0(\"2 assertions failed:\\n",
           " * Variable 'a': Element 0 is not >= 4\",\n         \".\\n *",
           "* Variable 'b': Must be of type 'character', not 'NULL'.\")),",
           "\n  fixed = TRUE)"),
    "# Testing fn(a = 1, a_fn = mean, b = \"ah\")",
    paste0("expect_error(\n  xpectr::strip_msg(fn(a = 1, a_fn = mean, b",
           " = \"ah\")),\n  xpectr::strip(paste0(\"2 assertions failed:",
           "\\n * Variable 'a': Element 0 is not >= 4\",\n         \".\\n",
           " * Variable 'b': Must have length 2, but has length 1.\")),",
           "\n  fixed = TRUE)"),
    paste0("## Finished testing 'fn'                                   ",
           "                 ####")
  )

  expect_equal(
    strip(gxs_function(fn, list(
        "a" = list(1, 2),
        a_fn = list(mean, sum),
        "b" = list("ah", "eh")
      ),
      out = "return")),
    strip(expected_tests),
    fixed = TRUE)
  expect_equal(
  length( gxs_function(fn, list(
        "a" = list(1, 2),
        a_fn = list(mean, sum),
        "b" = list("ah", "eh")
      ),
      out = "return") ),
  17L)

  eval_expectations(expected_tests, envir = current_envir)


  # Good baseline values  ####

  expected_tests2 <- c(
    "## Testing 'fn'                                                             ####\n## Initially generated by xpectr",
    "# Testing different combinations of argument values",
    "# Testing fn(a = 3, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), ...",
    "expect_error(\n  xpectr::strip_msg(fn(a = 3, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"hii\")),\n  xpectr::strip(\"1 assertions failed:\\n * Variable 'a': Element 0 is not >= 4.\"),\n  fixed = TRUE)",
    "# Testing fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), ...",
    "expect_error(\n  xpectr::strip_msg(fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = NA, f = \"hii\")),\n  xpectr::strip(\"1 assertions failed:\\n * Variable 'e': May not be NA.\"),\n  fixed = TRUE)",
    "# Testing fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), ...",
    "expect_equal(\n  fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"lol\"),\n  list(n = 15, m = \"lol: ahhh, ohhh\"))",
    "expect_equal(\n  names( fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"lol\") ),\n  c(\"n\", \"m\"),\n  fixed = TRUE)",
    "expect_equal(\n  length( fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"lol\") ),\n  2L)",
    "expect_equal(\n  sum(unlist(lapply( fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"lol\") , length))),\n  2L)",
    "# Testing fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), ...",
    "expect_error(\n  xpectr::strip_msg(fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = NA)),\n  xpectr::strip(\"1 assertions failed:\\n * Variable 'f': May not be NA.\"),\n  fixed = TRUE)",
    "# Testing fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), ...",
    "expect_error(\n  xpectr::strip_msg(fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = 3)),\n  xpectr::strip(paste0(\"1 assertions failed:\\n * Variable 'f': Must be of type 'stri\",\n         \"ng', not 'double'.\")),\n  fixed = TRUE)",
    "# Testing fn(a = 7, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), ...",
    "expect_error(\n  xpectr::strip_msg(fn(a = 7, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"hii\")),\n  xpectr::strip(\"1 assertions failed:\\n * Variable 'a': Element 1 is not <= 6.\"),\n  fixed = TRUE)",
    "# Testing fn(a = NA, a_fn = mean, b = c(\"ahhh\", \"ohhh\"),...",
    "expect_error(\n  xpectr::strip_msg(fn(a = NA, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"hii\")),\n  xpectr::strip(\"1 assertions failed:\\n * Variable 'a': May not be NA.\"),\n  fixed = TRUE)",
    "# Testing fn(a = 5, a_fn = sum, b = c(\"ahhh\", \"ohhh\"), d...",
    "expect_equal(\n  fn(a = 5, a_fn = sum, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"hii\"),\n  list(n = 15, m = \"hii: ahhh, ohhh\"))",
    "expect_equal(\n  names( fn(a = 5, a_fn = sum, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"hii\") ),\n  c(\"n\", \"m\"),\n  fixed = TRUE)",
    "expect_equal(\n  length( fn(a = 5, a_fn = sum, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"hii\") ),\n  2L)",
    "expect_equal(\n  sum(unlist(lapply( fn(a = 5, a_fn = sum, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"hii\") , length))),\n  2L)",
    "# Testing fn(a = 5, a_fn = mean, b = c(\"ehhh\", \"loool\"),...",
    "expect_equal(\n  fn(a = 5, a_fn = mean, b = c(\"ehhh\", \"loool\"), d = NULL, e = 3, f = \"hii\"),\n  list(n = 15, m = \"hii: ehhh, loool\"))",
    "expect_equal(\n  names( fn(a = 5, a_fn = mean, b = c(\"ehhh\", \"loool\"), d = NULL, e = 3, f = \"hii\") ),\n  c(\"n\", \"m\"),\n  fixed = TRUE)",
    "expect_equal(\n  length( fn(a = 5, a_fn = mean, b = c(\"ehhh\", \"loool\"), d = NULL, e = 3, f = \"hii\") ),\n  2L)",
    "expect_equal(\n  sum(unlist(lapply( fn(a = 5, a_fn = mean, b = c(\"ehhh\", \"loool\"), d = NULL, e = 3, f = \"hii\") , length))),\n  2L)",
    "# Testing fn(a = 5, a_fn = mean, b = c(\"jj\", \"ll\"), d = ...",
    "expect_error(\n  xpectr::strip_msg(fn(a = 5, a_fn = mean, b = c(\"jj\", \"ll\"), d = NULL, e = 3, f = \"hii\")),\n  xpectr::strip(paste0(\"1 assertions failed:\\n * Variable 'b': All elements must hav\",\n         \"e at least 3 characters.\")),\n  fixed = TRUE)",
    "# Testing fn(a = 5, a_fn = mean, b = c(\"ehhh\", \"loool\", ...",
    "expect_error(\n  xpectr::strip_msg(fn(a = 5, a_fn = mean, b = c(\"ehhh\", \"loool\", \"heeej\"), d = NULL, e = 3, f = \"hii\")),\n  xpectr::strip(paste0(\"1 assertions failed:\\n * Variable 'b': Must have length 2, b\",\n         \"ut has length 3.\")),\n  fixed = TRUE)",
    "# Testing fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), ...",
    "expect_error(\n  xpectr::strip_msg(fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = data.frame(col1 = c(1)), e = 3, f = \"hii\")),\n  xpectr::strip(paste0(\"1 assertions failed:\\n * Variable 'd': Must have at least 3 \",\n         \"rows, but has 1 rows.\")),\n  fixed = TRUE)",
    "# Testing fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), ...",
    "expect_equal(\n  fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 6, f = \"hii\"),\n  list(n = 30, m = \"hii: ahhh, ohhh\"))",
    "expect_equal(\n  names( fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 6, f = \"hii\") ),\n  c(\"n\", \"m\"),\n  fixed = TRUE)",
    "expect_equal(\n  length( fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 6, f = \"hii\") ),\n  2L)",
    "expect_equal(\n  sum(unlist(lapply( fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 6, f = \"hii\") , length))),\n  2L)",
    "# Testing fn(a = NULL, a_fn = mean, b = c(\"ahhh\", \"ohhh\"...",
    "expect_error(\n  xpectr::strip_msg(fn(a = NULL, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"hii\")),\n  xpectr::strip(paste0(\"1 assertions failed:\\n * Variable 'a': Must be of type 'numb\",\n         \"er', not 'NULL'.\")),\n  fixed = TRUE)",
    "# Testing fn(a = 5, a_fn = NULL, b = c(\"ahhh\", \"ohhh\"), ...",
    "expect_error(\n  xpectr::strip_msg(fn(a = 5, a_fn = NULL, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"hii\")),\n  xpectr::strip(paste0(\"1 assertions failed:\\n * Variable 'a_fn': Must be a function\",\n         \", not 'NULL'.\")),\n  fixed = TRUE)",
    "# Testing fn(a = 5, a_fn = mean, b = NULL, d = NULL, e =...",
    "expect_error(\n  xpectr::strip_msg(fn(a = 5, a_fn = mean, b = NULL, d = NULL, e = 3, f = \"hii\")),\n  xpectr::strip(paste0(\"1 assertions failed:\\n * Variable 'b': Must be of type 'char\",\n         \"acter', not 'NULL'.\")),\n  fixed = TRUE)",
    "# Testing fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), ...",
    "expect_equal(\n  fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"hii\"),\n  list(n = 15, m = \"hii: ahhh, ohhh\"))",
    "expect_equal(\n  names( fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"hii\") ),\n  c(\"n\", \"m\"),\n  fixed = TRUE)",
    "expect_equal(\n  length( fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"hii\") ),\n  2L)",
    "expect_equal(\n  sum(unlist(lapply( fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = \"hii\") , length))),\n  2L)",
    "# Testing fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), ...",
    "expect_equal(\n  fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = NULL, f = \"hii\"),\n  list(n = NaN, m = \"hii: ahhh, ohhh\"))",
    "expect_equal(\n  names( fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = NULL, f = \"hii\") ),\n  c(\"n\", \"m\"),\n  fixed = TRUE)",
    "expect_equal(\n  length( fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = NULL, f = \"hii\") ),\n  2L)",
    "expect_equal(\n  sum(unlist(lapply( fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = NULL, f = \"hii\") , length))),\n  2L)",
    "# Testing fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), ...",
    "expect_error(\n  xpectr::strip_msg(fn(a = 5, a_fn = mean, b = c(\"ahhh\", \"ohhh\"), d = NULL, e = 3, f = NULL)),\n  xpectr::strip(paste0(\"1 assertions failed:\\n * Variable 'f': Must be of type 'stri\",\n         \"ng', not 'NULL'.\")),\n  fixed = TRUE)",
    "## Finished testing 'fn'                                                    ####"
  )

  expect_equal(
    strip(gxs_function(fn, list(
      "a" = list(5, 3, 7, NA),
      a_fn = list(mean, sum),
      "b" = list(c("ahhh","ohhh"), c("ehhh","loool"), c("jj","ll"),  c("ehhh","loool", "heeej")),
      "d" = list(NULL, data.frame("col1" = c(1))),
      "e" = list(3, 6, NA),
      "f" = list("hii", "lol", NA, 3)
    ),
    out = "return")),
    strip(expected_tests2),
    fixed = TRUE)

  ## Second function

  fn2 <- function(x, y, z){
    if (x>3) stop("'x' > 3")
    if (y<0) warning("'y'<0")
    if (z==10) message("'z' was 10!")
    x + y + z
  }

  fn2_expected_tests <- c(
    "## Testing 'fn2'                                                            ####\n## Initially generated by xpectr",
    "# Testing different combinations of argument values",
    "# Testing fn2(x = 4, y = 0, z = 5)",
    "expect_error(\n  xpectr::strip_msg(fn2(x = 4, y = 0, z = 5)),\n  xpectr::strip(\"'x' > 3\"),\n  fixed = TRUE)",
    "# Testing fn2(x = NA, y = 0, z = 5)",
    "expect_error(\n  xpectr::strip_msg(fn2(x = NA, y = 0, z = 5)),\n  xpectr::strip(\"missing value where TRUE/FALSE needed\"),\n  fixed = TRUE)",
    "# Testing fn2(x = 2, y = -1, z = 5)",
    "expect_warning(\n  xpectr::strip_msg(fn2(x = 2, y = -1, z = 5)),\n  xpectr::strip(\"'y'<0\"),\n  fixed = TRUE)",
    "# Testing fn2(x = 2, y = 0, z = 10)",
    "expect_message(\n  xpectr::strip_msg(fn2(x = 2, y = 0, z = 10)),\n  xpectr::strip(\"'z' was 10!\\n\"),\n  fixed = TRUE)",
    "# Testing fn2(x = 2, y = 0, z = 15)",
    "expect_equal(\n  fn2(x = 2, y = 0, z = 15),\n  17,\n  tolerance = 1e-4)",
    "expect_equal(\n  names( fn2(x = 2, y = 0, z = 15) ),\n  NULL,\n  fixed = TRUE)",
    "expect_equal(\n  length( fn2(x = 2, y = 0, z = 15) ),\n  1L)",
    "expect_equal(\n  sum(unlist(lapply( fn2(x = 2, y = 0, z = 15) , length))),\n  1L)",
    "# Testing fn2(x = 2, y = 0, z = 5)",
    "expect_equal(\n  fn2(x = 2, y = 0, z = 5),\n  7,\n  tolerance = 1e-4)",
    "expect_equal(\n  names( fn2(x = 2, y = 0, z = 5) ),\n  NULL,\n  fixed = TRUE)",
    "expect_equal(\n  length( fn2(x = 2, y = 0, z = 5) ),\n  1L)",
    "expect_equal(\n  sum(unlist(lapply( fn2(x = 2, y = 0, z = 5) , length))),\n  1L)",
    "# Testing fn2(x = NULL, y = 0, z = 5)",
    paste0("expect_error(\n  xpectr::strip_msg(fn2(x = NULL, y = 0, z =",
           " 5)),\n  xpectr::strip(\"argument is of length zero\"),\n  f",
           "ixed = TRUE)"),
    "# Testing fn2(x = 2, y = NULL, z = 5)",
    paste0("expect_error(\n  xpectr::strip_msg(fn2(x = 2, y = NULL, z =",
           " 5)),\n  xpectr::strip(\"argument is of length zero\"),\n  f",
           "ixed = TRUE)"),
    "# Testing fn2(x = 2, y = 0, z = NULL)",
    paste0("expect_error(\n  xpectr::strip_msg(fn2(x = 2, y = 0, z = NU",
           "LL)),\n  xpectr::strip(\"argument is of length zero\"),\n  f",
           "ixed = TRUE)"),
    "## Finished testing 'fn2'                                                   ####"
  )

  # Create expectations
  # Note: define the list in the call
  expect_equal(strip(gxs_function(fn2,
               list("x" = list(2, 4, NA),
                    "y" = list(0, -1),
                    "z" = list(5, 10, 15)),
               out = "return")),
               strip(fn2_expected_tests),
               fixed = TRUE)


})
