library(xpectr)
context("gxs_selection()")

test_that("expectations are created properly with gxs_selection()", {
  df1 <- tibble::tibble("a" = c(1, 2, 3, 4), "b" = c("a", "f", "g", "s"))
  df1$c <- list(list(1, 2, 3), list(2, 3, 4, 5), list(2, 3, 7, 21, 2), list(2))
  df1[["d"]] <- list(a = list(2, 4), b = list(3), c = list(1), d = list(2, 3))
  # Add factor
  df1$f <- factor(df1$a)

  # We're not getting it from parent environment
  # so we supply current environment
  current_envir <- sys.frame(which = sys.nframe())

})

test_that("data frame expectations are created properly with gxs_selection()", {

  set_test_seed(1)
  df1 <- tibble::tibble("a" = c(1, 2, 3, 4), "b" = c("a", "f", "g", "s"))

  ## Testing 'gxs_selection("df1", out = "return")'                         ####
  ## Initially generated by xpectr
  # Assigning output
  output_12654 <- gxs_selection("df1", out = "return")
  # Testing class
  expect_equal(
    class(output_12654),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_12654,
    type = "list")
  # Testing values
  expect_equal(
    output_12654,
    list("## Testing 'df1'                                                            ####\n## Initially generated by xpectr",
          "# Testing class", "expect_equal(\n  class(df1),\n  c(\"tbl_df\", \"tbl\", \"data.frame\"),\n  fixed = TRUE)",
          "# Testing column values", "expect_equal(\n  df1[[\"a\"]],\n  c(1, 2, 3, 4),\n  tolerance = 1e-4)",
          "expect_equal(\n  df1[[\"b\"]],\n  c(\"a\", \"f\", \"g\", \"s\"),\n  fixed = TRUE)",
          "# Testing column names", "expect_equal(\n  names(df1),\n  c(\"a\", \"b\"),\n  fixed = TRUE)",
          "# Testing column classes", "expect_equal(\n  xpectr::element_classes(df1),\n  c(\"numeric\", \"character\"),\n  fixed = TRUE)",
          "# Testing column types", "expect_equal(\n  xpectr::element_types(df1),\n  c(\"double\", \"character\"),\n  fixed = TRUE)",
          "# Testing dimensions", "expect_equal(\n  dim(df1),\n  c(4L, 2L))",
          "# Testing group keys", "expect_equal(\n  colnames(dplyr::group_keys(df1)),\n  character(0),\n  fixed = TRUE)",
          "## Finished testing 'df1'                                                   ####"))
  # Testing names
  expect_equal(
    names(output_12654),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_12654),
    17L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_12654)),
    17L)
  ## Finished testing 'gxs_selection("df1", out = "return")'                ####

  ## Testing 'gxs_selection("tibble::tibble('a' = c(1, 2, ...'              ####
  ## Initially generated by xpectr
  # Assigning output
  output_18982 <- gxs_selection("tibble::tibble('a' = c(1, 2, 3, 4), 'b' = c('b', 'f', 'g', 's'))", out = "return")
  # Testing class
  expect_equal(
    class(output_18982),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_18982,
    type = "list")
  # Testing values
  expect_equal(
    output_18982,
    list("## Testing 'tibble::tibble('a' = c(1, 2, 3, 4), 'b' = c('b...'              ####\n## Initially generated by xpectr",
          "# Assigning output", "output_12654 <- tibble::tibble('a' = c(1, 2, 3, 4), 'b' = c('b', 'f', 'g', 's'))",
          "# Testing class", "expect_equal(\n  class(output_12654),\n  c(\"tbl_df\", \"tbl\", \"data.frame\"),\n  fixed = TRUE)",
          "# Testing column values", "expect_equal(\n  output_12654[[\"a\"]],\n  c(1, 2, 3, 4),\n  tolerance = 1e-4)",
          "expect_equal(\n  output_12654[[\"b\"]],\n  c(\"b\", \"f\", \"g\", \"s\"),\n  fixed = TRUE)",
          "# Testing column names", "expect_equal(\n  names(output_12654),\n  c(\"a\", \"b\"),\n  fixed = TRUE)",
          "# Testing column classes", "expect_equal(\n  xpectr::element_classes(output_12654),\n  c(\"numeric\", \"character\"),\n  fixed = TRUE)",
          "# Testing column types", "expect_equal(\n  xpectr::element_types(output_12654),\n  c(\"double\", \"character\"),\n  fixed = TRUE)",
          "# Testing dimensions", "expect_equal(\n  dim(output_12654),\n  c(4L, 2L))",
          "# Testing group keys", "expect_equal(\n  colnames(dplyr::group_keys(output_12654)),\n  character(0),\n  fixed = TRUE)",
          "## Finished testing 'tibble::tibble('a' = c(1, 2, 3, 4), 'b' = c('b...'     ####"))
  # Testing names
  expect_equal(
    names(output_18982),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_18982),
    19L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_18982)),
    19L)
  ## Finished testing 'gxs_selection("tibble::tibble('a' = c(1, 2, ...'     ####

  df1$c <- list(list(1, 2, 3), list(2, 3, 4, 5), list(2, 3, 7, 21, 2), list(2))


  ## Testing 'gxs_selection("df1", out = "return")'                         ####
  ## Initially generated by xpectr
  # Testing side effects
  expect_warning(
    xpectr::strip_msg(gxs_selection("df1", out = "return")),
    xpectr::strip("Skipped column c."),
    fixed = TRUE)
  ## Finished testing 'gxs_selection("df1", out = "return")'                ####


})

test_that("list of lists expectations are created properly with gxs_selection()", {

  l <- list(list(1, 2, 3), list(2, 3, 4, list(5, 3)), list(2, 3, 7, 21, 2), list(2))

  ## Testing 'gxs_selection("l", out = "return")'                           ####
  ## Initially generated by xpectr
  # Assigning output
  output_19483 <- gxs_selection("l", out = "return")
  # Testing class
  expect_equal(
    class(output_19483),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_19483,
    type = "list")
  # Testing values
  expect_equal(
    output_19483,
    list("## Testing 'l'                                                              ####\n## Initially generated by xpectr",
          "# Testing class", "expect_equal(\n  class(l),\n  \"list\",\n  fixed = TRUE)",
          "# Testing type", "expect_type(\n  l,\n  type = \"list\")",
          "# Testing values", "expect_equal(\n  l,\n  list(list(1, 2, 3), list(2, 3, 4, list(5, 3)), list(2, 3, 7, 21,\n    2), list(2)))",
          "# Testing names", "expect_equal(\n  names(l),\n  NULL,\n  fixed = TRUE)",
          "# Testing length", "expect_equal(\n  length(l),\n  4L)",
          "# Testing sum of element lengths", "expect_equal(\n  sum(xpectr::element_lengths(l)),\n  13L)",
          "## Finished testing 'l'                                                     ####"))
  # Testing names
  expect_equal(
    names(output_19483),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_19483),
    14L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_19483)),
    14L)
  ## Finished testing 'gxs_selection("l", out = "return")'                  ####

})

test_that("vector expectations are created properly with gxs_selection()", {

  vec_1 <- c(1,2,3,4,5,6,NA)

  ## Testing 'gxs_selection("vec_1", out = "return")'                       ####
  ## Initially generated by xpectr
  # Assigning output
  output_13720 <- gxs_selection("vec_1", out = "return")
  # Testing class
  expect_equal(
    class(output_13720),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_13720,
    type = "list")
  # Testing values
  expect_equal(
    output_13720,
    list(
      "## Testing 'vec_1'                                                          ####\n## Initially generated by xpectr",
      "# Testing class",
      "expect_equal(\n  class(vec_1),\n  \"numeric\",\n  fixed = TRUE)",
      "# Testing type",
      "expect_type(\n  vec_1,\n  type = \"double\")",
      "# Testing values",
      "expect_equal(\n  vec_1,\n  c(1, 2, 3, 4, 5, 6, NA),\n  tolerance = 1e-4)",
      "# Testing names",
      "expect_equal(\n  names(vec_1),\n  NULL,\n  fixed = TRUE)",
      "# Testing length",
      "expect_equal(\n  length(vec_1),\n  7L)",
      "# Testing sum of element lengths",
      "expect_equal(\n  sum(xpectr::element_lengths(vec_1)),\n  7L)",
      "## Finished testing 'vec_1'                                                 ####"
    ))
  # Testing names
  expect_equal(
    names(output_13720),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_13720),
    14L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_13720)),
    14L)
  ## Finished testing 'gxs_selection("vec_1", out = "return")'              ####

})

test_that("vector expectations are created properly with gxs_selection()", {

  fact_1 <- factor(as.character(c(1,2,3,4,5,6,NA)))

  ## Testing 'gxs_selection("fact_1", out = "return")'                      ####
  ## Initially generated by xpectr
  # Assigning output
  output_15727 <- gxs_selection("fact_1", out = "return")
  # Testing class
  expect_equal(
    class(output_15727),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_15727,
    type = "character")
  # Testing values
  expect_equal(
    output_15727,
    c(
      "## Testing 'fact_1'                                                         ####\n## Initially generated by xpectr",
      "# Testing is factor",
      "expect_true(\n  is.factor(fact_1))",
      "# Testing values",
      "expect_equal(\n  as.character(fact_1),\n  c(\"1\", \"2\", \"3\", \"4\", \"5\", \"6\", NA),\n  fixed = TRUE)",
      "# Testing names",
      "expect_equal(\n  names(fact_1),\n  NULL,\n  fixed = TRUE)",
      "# Testing length",
      "expect_equal(\n  length(fact_1),\n  7L)",
      "# Testing number of levels",
      "expect_equal(\n  nlevels(fact_1),\n  6L)",
      "# Testing levels",
      "expect_equal(\n  levels(fact_1),\n  c(\"1\", \"2\", \"3\", \"4\", \"5\", \"6\"),\n  fixed = TRUE)",
      "## Finished testing 'fact_1'                                                ####"
    ),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_15727),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_15727),
    14L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_15727)),
    14L)
  ## Finished testing 'gxs_selection("fact_1", out = "return")'             ####


})

test_that("NULL expectations are created properly with gxs_selection()", {

  ## Testing 'gxs_selection("NULL", out = "return")'                        ####
  ## Initially generated by xpectr
  # Assigning output
  output_14242 <- gxs_selection("NULL", out = "return")
  # Testing class
  expect_equal(
    class(output_14242),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_14242,
    type = "character")
  # Testing values
  expect_equal(
    output_14242,
    c(
      "## Testing 'NULL'                                                           ####\n## Initially generated by xpectr",
      "# Testing is NULL",
      "expect_true(\n  is.null(NULL))",
      "## Finished testing 'NULL'                                                  ####"
    ),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_14242),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_14242),
    4L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_14242)),
    4L)
  ## Finished testing 'gxs_selection("NULL", out = "return")'               ####

})

test_that("NA expectations are created properly with gxs_selection()", {

  ## Testing 'gxs_selection("NA", out = "return")'                          ####
  ## Initially generated by xpectr
  # Assigning output
  output_14817 <- gxs_selection("NA", out = "return")
  # Testing class
  expect_equal(
    class(output_14817),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_14817,
    type = "list")
  # Testing values
  expect_equal(
    output_14817,
    list("## Testing 'NA'                                                             ####\n## Initially generated by xpectr",
          "# Testing class", "expect_equal(\n  class(NA),\n  \"logical\",\n  fixed = TRUE)",
          "# Testing type", "expect_type(\n  NA,\n  type = \"logical\")",
          "# Testing values", "expect_equal(\n  NA,\n  NA)", "# Testing names",
          "expect_equal(\n  names(NA),\n  NULL,\n  fixed = TRUE)", "# Testing length",
          "expect_equal(\n  length(NA),\n  1L)", "# Testing sum of element lengths",
          "expect_equal(\n  sum(xpectr::element_lengths(NA)),\n  1L)",
          "## Finished testing 'NA'                                                    ####"))
  # Testing names
  expect_equal(
    names(output_14817),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_14817),
    14L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_14817)),
    14L)
  ## Finished testing 'gxs_selection("NA", out = "return")'                 ####

})

test_that("single number expectations are created properly with gxs_selection()", {

  ## Testing 'gxs_selection("1", out = "return")'                           ####
  ## Initially generated by xpectr
  # Assigning output
  output_17871 <- gxs_selection("1", out = "return")
  # Testing class
  expect_equal(
    class(output_17871),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_17871,
    type = "list")
  # Testing values
  expect_equal(
    output_17871,
    list("## Testing '1'                                                              ####\n## Initially generated by xpectr",
          "# Testing class", "expect_equal(\n  class(1),\n  \"numeric\",\n  fixed = TRUE)",
          "# Testing type", "expect_type(\n  1,\n  type = \"double\")",
          "# Testing values", "expect_equal(\n  1,\n  1,\n  tolerance = 1e-4)",
          "# Testing names", "expect_equal(\n  names(1),\n  NULL,\n  fixed = TRUE)",
          "# Testing length", "expect_equal(\n  length(1),\n  1L)",
          "# Testing sum of element lengths", "expect_equal(\n  sum(xpectr::element_lengths(1)),\n  1L)",
          "## Finished testing '1'                                                     ####"))
  # Testing names
  expect_equal(
    names(output_17871),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_17871),
    14L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_17871)),
    14L)
  ## Finished testing 'gxs_selection("1", out = "return")'                  ####

})

test_that("missing variable expectations are created properly with gxs_selection()", {

  ## Testing 'gxs_selection("MISSINGVAR", out = "return")'                  ####
  ## Initially generated by xpectr
  # Assigning output
  output_11242 <- gxs_selection("MISSINGVAR", out = "return")
  # Testing class
  expect_equal(
    class(output_11242),
    "list",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_11242,
    type = "list")
  # Testing values
  expect_equal(
    output_11242,
    list(
      "## Testing 'MISSINGVAR'                                                     ####\n## Initially generated by xpectr",
      "# Testing side effects",
      "expect_error(\n  xpectr::strip_msg(MISSINGVAR),\n  xpectr::strip(\"object 'MISSINGVAR' not found\"),\n  fixed = TRUE)",
      "## Finished testing 'MISSINGVAR'                                            ####"
    ))
  # Testing names
  expect_equal(
    names(output_11242),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_11242),
    4L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_11242)),
    4L)
  ## Finished testing 'gxs_selection("MISSINGVAR", out = "return")'         ####

})
