on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]


name: R-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'devel'}
          - {os: macOS-latest,   r: 'release'}
          - {os: macOS-latest,   r: 'oldrel'}

          - {os: windows-latest, r: 'devel'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'oldrel'}

          - {os: ubuntu-18.04,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-18.04,   r: 'release'}
          - {os: ubuntu-18.04,   r: 'oldrel'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_CRAN_INCOMING_: false
      _R_CHECK_FORCE_SUGGESTS_: false
      _R_CHECK_STOP_ON_INVALID_NUMERIC_VERSION_INPUTS_: true

    steps:
      - uses: actions/checkout@v3

      # Always try to use the latest pandoc version
      # https://github.com/jgm/pandoc/releases
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.11'

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      # TODO: Check which of the ignore conditions are still relevant given the
      # current suggested dependencies and the minimum supported R version.
      # Update if anything out of date or not needed anymore.
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          extra-packages: |
            any::rcmdcheck
          needs: check

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      # Don't error on "note" because if any of the suggested packages are not available
      # for a given R version, this generates a NOTE causing unnecessary build failure
      - uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"warning"'
          upload-snapshots: true

